apiVersion: v1
kind: Service
metadata:
  name: simple-webapp-docker
spec:
  selector:
    ## Change for deploymentconfig
#    docker-registry: default
    deploymentconfig: simple-webapp-docker
  ports:
    - nodePort: 0
      port: 8080
      protocol: TCP
      targetPort: 8080