kind: "DeploymentConfig"
apiVersion: "v1"
metadata:
  name: "nginx-test"
spec:
  template:
    metadata:
      labels:
        name: "nginx-test"
    spec:
      containers:
        - name: "nginx-test"
          image: "nginx-proxy"
          ports:
            - containerPort: 8080
              protocol: "TCP"
  replicas: 1
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
      imageChangeParams:
        automatic: true
        containerNames:
          - "nginx-test"
        from:
          kind: "ImageStreamTag"
          name: "nginx-proxy:latest"
  strategy:
    type: "Rolling"
  paused: false
  revisionHistoryLimit: 2
  minReadySeconds: 0 