apiVersion: v1
kind: Template
metadata:
  creatingTimestamp: null
  name: example-voting-app-template
# Identified the Components: We identified all the components used in the example voting application, including Secrets,
# Build Configurations, Deployment Configurations, Image Streams, Services, and Routes.
objects:
  apiVersion: vl
  kind: Template

  metadata:
    creationTimestamp: null
    name: example-voting-app-template

  objects:
    - apiVersion: vl
      data:
        database-name: db
        database-password: postgres_password
        database-user: postgres_user
      kind: Secret
      metadata:
        name: db

    - apiVersion: vl
      data:
        database-password: redis_password
      kind: Secret
      metadata:
        name: redis