apiVersion: v1
kind: Template
metadata:
  name: prometheus-template
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: prometheus-config
    data:
      prometheus.yml: |
        global:
          scrape_interval: 15s
        
        scrape_configs:
          - job_name: 'my-go-app'
            static_configs:
            - targets: ['172.17.0.8:8080']
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: go-app-deployment
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: go-app
      template:
        metadata:
          labels:
            app: go-app
        spec:
          containers:
            - name: go-app
              image: quay.io/projectquay/golang:1.17
              ports:
                - containerPort: 8080
          volumes:
            - name: config-volume
              configMap:
                name: prometheus-config
  - apiVersion: v1
    kind: Service
    metadata:
      name: go-app-service
    spec:
      selector:
        app: go-app
      ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
  - apiVersion: v1
    kind: Service
    metadata:
      name: prometheus-service
    spec:
      selector:
        app: prometheus
      ports:
        - protocol: TCP
          port: 9090
          targetPort: 9090
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: prometheus-route
    spec:
      host: prometheus.example.com
      to:
        kind: Service
        name: prometheus-service
        weight: 100
      port:
        targetPort: 9090
